export const words = [
  { word: "react", hint: "Library used to build reusable UI components" },
  { word: "javascript", hint: "Language executed inside browsers for dynamic behavior" },
  { word: "typescript", hint: "JavaScript variant that enforces static type safety" },
  { word: "component", hint: "Independent UI block that manages its own logic" },
  { word: "developer", hint: "Professional who creates and maintains software" },
  { word: "variable", hint: "Named reference that holds a changing value" },
  { word: "function", hint: "Reusable block that executes when called" },
  { word: "framework", hint: "Predefined structure for building applications faster" },
  { word: "database", hint: "Organized collection of data accessible by queries" },
  { word: "compiler", hint: "Converts source code into machine-understandable format" },
  { word: "algorithm", hint: "Finite steps designed to solve a specific problem" },
  { word: "encryption", hint: "Process of converting data to unreadable format using keys" },
  { word: "processor", hint: "Hardware unit responsible for executing instructions" },
  { word: "debugging", hint: "Systematic process of identifying and fixing code flaws" },
  { word: "bandwidth", hint: "Maximum data transfer rate of a network" },
  { word: "syntax", hint: "Set of rules defining how statements must be written" },
  { word: "iteration", hint: "Repeating instructions until a condition is satisfied" },
  { word: "recursion", hint: "Function that solves a problem by calling itself" },
  { word: "interface", hint: "Contract defining methods without implementation" },
  { word: "virtualization", hint: "Creating simulated hardware environments on one machine" },
  { word: "authentication", hint: "Verifying identity using credentials" },
  { word: "authorization", hint: "Determining what actions a verified user can perform" },
  { word: "optimization", hint: "Improving code performance and efficiency" },
  { word: "synchronization", hint: "Ensuring multiple operations occur in a coordinated manner" },
  { word: "transformation", hint: "Converting data from one structure to another" },
  { word: "deployment", hint: "Moving software from development to live environment" },
  { word: "middleware", hint: "Software acting as a bridge between different systems" },

  // --- General Knowledge (GK) Words ---
  { word: "oxygen", hint: "Element essential for human respiration, atomic number 8" },
  { word: "gravity", hint: "Force that attracts objects toward a mass like Earth" },
  { word: "planet", hint: "Celestial body orbiting a star with its own gravity" },
  { word: "galaxy", hint: "Huge system of stars, dust, and gas; Milky Way is one" },
  { word: "volcano", hint: "Opening in Earth's crust that erupts lava" },
  { word: "glacier", hint: "Large mass of slowly moving ice" },
  { word: "economics", hint: "Study of production, consumption and wealth distribution" },
  { word: "democracy", hint: "Government where power lies with citizens through elections" },
  { word: "constitution", hint: "Fundamental set of laws governing a country" },
  { word: "hemisphere", hint: "Half of the Earth divided by equator or meridian" },
  { word: "photosynthesis", hint: "Process where plants convert sunlight into energy" },
  { word: "evaporation", hint: "Process where liquid turns into vapor due to heat" },
  { word: "microscope", hint: "Tool used to view organisms smaller than visible scale" },
  { word: "telescope", hint: "Optical instrument for viewing distant celestial objects" },
  { word: "ecosystem", hint: "Community where organisms interact with their environment" },
  { word: "hypothesis", hint: "Logical assumption that can be tested in experiments" },
  { word: "friction", hint: "Force that resists motion between two surfaces" },
  { word: "inertia", hint: "Property of matter resisting changes in motion" },
  { word: "photosphere", hint: "The visible glowing surface of the Sun" },

  // --- Animals ---
{ word: "tiger", hint: "Big cat with orange fur and black stripes" },
{ word: "elephant", hint: "Very large animal with a long trunk" },
{ word: "kangaroo", hint: "Australian animal that jumps with strong legs" },
{ word: "dolphin", hint: "Smart sea animal that swims fast" },
{ word: "giraffe", hint: "Tall animal with a very long neck" },
{ word: "penguin", hint: "Bird that cannot fly but swims well" },
{ word: "lion", hint: "Big cat with a mane, called the king of animals" },
{ word: "zebra", hint: "Animal with black and white stripes" },
{ word: "bear", hint: "Large animal that lives in forests" },
{ word: "parrot", hint: "Colorful bird that can mimic human speech" }
];
