export const words = [
  { word: "react", hint: "JavaScript library for building user interfaces" },
  { word: "javascript", hint: "Language that powers dynamic web pages" },
  { word: "typescript", hint: "JavaScript with optional static typing" },
  { word: "component", hint: "Reusable UI building piece in React" },
  { word: "developer", hint: "Person who writes software" },
  { word: "variable", hint: "Container that stores a value" },
  { word: "function", hint: "Block of code that performs an operation" },
  { word: "framework", hint: "Provides structure for building applications" },
  { word: "database", hint: "Stores structured information" },
  { word: "compiler", hint: "Turns source code into machine code" },
  { word: "algorithm", hint: "Step-by-step method to solve a problem" },
  { word: "encryption", hint: "Converts data to unreadable form for security" },
  { word: "processor", hint: "CPU that executes instructions" },
  { word: "debugging", hint: "Finding and fixing programming errors" },
  { word: "bandwidth", hint: "Rate of data transfer per second" },
  { word: "syntax", hint: "Rules defining valid code structure" },
  { word: "iteration", hint: "Repeated execution of instructions" },
  { word: "recursion", hint: "Function calling itself repeatedly" },
  { word: "interface", hint: "Boundary defining how systems interact" },
  { word: "compiler", hint: "Software that converts code into executables" },
  { word: "virtualization", hint: "Running multiple OS on one machine" },
  { word: "authentication", hint: "Process of verifying user identity" },
  { word: "authorization", hint: "Determines what a user can access" },
  { word: "optimization", hint: "Making software faster or more efficient" },
  { word: "synchronization", hint: "Keeping operations in coordinated timing" },
  { word: "transformation", hint: "Converting data from one format to another" },
  { word: "deployment", hint: "Releasing software to production" },
  { word: "middleware", hint: "Software connecting different applications" },
  { word: "oxygen", hint: "Essential gas for respiration" },
  { word: "gravity", hint: "Force pulling objects toward Earth" },
  { word: "planet", hint: "Celestial body orbiting a star" },
  { word: "science", hint: "Study of the natural world" },
  { word: "energy", hint: "Ability to do work" },
  { word: "memory", hint: "Ability to retain and recall information" },
  { word: "umbrella", hint: "Used for protection from rain" },
  { word: "library", hint: "Place storing books for reading" },
  { word: "architecture", hint: "Design structure of buildings or systems" },
  { word: "hypothesis", hint: "Testable explanation for an observation" },
  { word: "photosynthesis", hint: "Plants converting sunlight to energy" },
  { word: "friction", hint: "Force resisting motion between surfaces" },
  { word: "evaporation", hint: "Liquid turning into vapor" },
  { word: "microscope", hint: "Device used to view tiny objects" },
  { word: "telescope", hint: "Instrument to observe distant objects" },
  { word: "voltage", hint: "Electric potential difference" },
  { word: "circuit", hint: "Path for electric current" },
  { word: "radiation", hint: "Energy emitted in waves or particles" },
  { word: "inertia", hint: "Object's resistance to motion change" },
  { word: "ecosystem", hint: "Community of organisms interacting" },
  { word: "photosphere", hint: "Visible surface layer of the Sun" },
  { word: "tiger", hint: "Largest cat with black stripes" },
  { word: "elephant", hint: "Giant land animal with a trunk" },
  { word: "kangaroo", hint: "Australian animal that hops" },
  { word: "dolphin", hint: "Intelligent marine mammal" },
  { word: "giraffe", hint: "Tallest land animal" },
  { word: "penguin", hint: "Flightless bird living in cold areas" },
  { word: "cheetah", hint: "Fastest land animal" },
  { word: "panda", hint: "Black and white bamboo-eating bear" },
  { word: "lion", hint: "Known as the king of the jungle" },
  { word: "zebra", hint: "Striped black-and-white animal" },
  { word: "rhino", hint: "Thick-skinned animal with a horn" },
  { word: "hippopotamus", hint: "Large water-loving mammal" },
  { word: "wolf", hint: "Wild ancestor of dogs" },
  { word: "fox", hint: "Small carnivore with a bushy tail" },
  { word: "bear", hint: "Large omnivore found in forests" },
  { word: "camel", hint: "Desert animal with humps" },
  { word: "gorilla", hint: "Largest living primate" },
  { word: "monkey", hint: "Tree-dwelling primate" },
  { word: "buffalo", hint: "Large animal often found near water" },
  { word: "leopard", hint: "Spotted wild cat that climbs trees" },
  { word: "jaguar", hint: "Big cat known for powerful bite" },
  { word: "otter", hint: "Playful semi-aquatic mammal" },
  { word: "koala", hint: "Tree-dwelling Australian marsupial" },
  { word: "bat", hint: "Only flying mammal" },
  { word: "owl", hint: "Nocturnal bird with silent wings" },
  { word: "eagle", hint: "Large bird known for sharp vision" },
  { word: "vulture", hint: "Scavenger bird with broad wings" },
  { word: "shark", hint: "Predatory fish with sharp teeth" },
  { word: "whale", hint: "Largest animal on Earth" },
  { word: "octopus", hint: "Eight-armed intelligent sea creature" },
  { word: "snake", hint: "Legless reptile that slithers" },
  { word: "crocodile", hint: "Reptile with powerful jaws" },
  { word: "frog", hint: "Amphibian known for jumping" },
  { word: "sparrow", hint: "Small common bird" },
  { word: "parrot", hint: "Colorful bird that mimics sounds" },
  { word: "peacock", hint: "Bird famous for its colorful tail" }
];
